---
- name: "Get Nessus Agent from repository"
  when: nessus_agent_install_method != "url"
  block:
    - name: Install Nessus Agent from repo
      ansible.builtin.package:
        name: "{{ nessus_agent_package }}"
        update_cache: yes
      when: "'.rpm' not in nessus_agent_package"

    - name: Install Nessus Agent from .rpm package
      ansible.builtin.package:
        rpm: "{{ nessus_agent_package }}"
      when: "'.rpm' in nessus_agent_package"

- name: "Get Nessus Agent from URL"
  when: nessus_agent_install_method == "url"
  block:
    - name: Download Nessus Agent
      ansible.builtin.get_url:
        url: "{{ nessus_agent_download_url }}"
        dest: "{{ nessus_agent_temp_dir }}/NessusAgent.rpm"
        checksum: "{{ nessus_agent_file_checksum }}"
        mode: "0644"

    - name: Perform Agent installation
      ansible.builtin.yum:
        name: "{{ nessus_agent_temp_dir }}/NessusAgent.rpm"
        state: present
        disable_gpg_check: yes
