---
- name: "Get Nessus Agent from repository"
  block:
    - name: Install Nessus Agent from repo
      ansible.builtin.package:
        name: "{{ nessus_agent_package }}"
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
      when: "'.deb' not in nessus_agent_package"

    - name: Install Nessus Agent from .deb package
      ansible.builtin.apt:
        deb: "{{ nessus_agent_package }}"
      when: "'.deb' in nessus_agent_package"
  when: nessus_agent_install_method != "url"

- name: "Get Nessus Agent from URL"
  block:
    - name: Download Nessus Agent
      ansible.builtin.get_url:
        url: "{{ nessus_agent_download_url }}"
        dest: "{{ nessus_agent_temp_dir }}/NessusAgent.deb"
        checksum: "{{ nessus_agent_file_checksum }}"

    - name: Perform Agent installation
      ansible.builtin.apt:
        deb: "{{ nessus_agent_temp_dir }}/NessusAgent.deb"
  when: nessus_agent_install_method == "url"
